apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: igneous
spec:
  replicas: 16
  template:
    metadata:
      labels:
        app: igneous
    spec:
      containers:
        - name: igneous
          image: seunglab/igneous:master
          volumeMounts:
          - name: secrets
            mountPath: "/secrets"
            readOnly: true
          - name: tmp
            mountPath: "/tmp"
            readOnly: false
          imagePullPolicy: Always
          resources:
            requests:
              memory: 2.5Gi
          env:
            - name: QUEUE_TYPE
              value: aws
            - name: SQS_URL
              value: 'https://sqs.us-east-1.amazonaws.com/098703261575/wms-pull-queue'
            - name: LEASE_SECONDS
              value: "800"
      volumes:
      - name: secrets
        secret:
          secretName: secrets
      - name: tmp
        emptyDir: { medium: "Memory" }